### ISSUE TITLE
Crear la base de datos; y mostar evidencia de las tablas donde se muestren los campos

### ISSUE THREAD

**Issue by DianaBejarano** [DianaBejarano/MascotaFeliz#5]

**Comment by jorabe2021** [comment]
![Image](https://user-images.githubusercontent.com/89425066/187058337-db7ad4b9-e7b0-44f6-9103-7d01220a1a87.JPG)

**Comment by jorabe2021** [comment]
![Image](https://user-images.githubusercontent.com/89425066/187058355-76069a6c-e042-4a76-b57a-2f9adde08660.JPG)
